name: Spiffy
version: 0.25
abstract: Spiffy Perl Interface Framework For You
author: Ingy döt Net <ingy@cpan.org>
license: perl
distribution_type: module
requires:
  perl: 5.6.1
  Filter::Util::Call: 0
  Scalar::Util: 0
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.47
