---
abstract: 'Spiffy Perl Interface Framework For You'
author:
  - 'Ingy döt Net <ingy@ingy.net>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Spiffy
name: Spiffy
no_index:
  directory:
    - inc
    - t
requires:
  perl: 5.6.1
resources:
  homepage: https://github.com/ingydotnet/spiffy-pm/tree
  license: http://dev.perl.org/licenses/
  repository:
    type: git
    url: git://github.com/ingydotnet/spiffy-pm.git
    web: https://github.com/ingydotnet/spiffy-pm/tree
version: 0.31
