name: Spiffy
version: 0.13
abstract: Spiffy Perl Interface Framework For You
author: Brian Ingerson <ingy@cpan.org>
license: perl
distribution_type: module
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.31
